# Site settings
title: Maek Twain aka Saransh S.
email: saransh@theupscale.in
description: "Hey, I am Saransh Sharma serving as CTO of Upscale PVT LTD, a research oriented organization which focues on Big Data and Open Source Business Consulting, I am a curious mathematician, and a upcoming Researcher and a Computer Scientist, currently i am pursuing my Engg. Degree From MD University."
baseurl: ""
url: "http://maektwain.com"
twitter_username: saranshlovesr
github_username:  maektwain

# Build settings
markdown: kramdown
permalink: pretty
