# Site settings
title: Maek Twain aka Saransh S.
email: saransh@theupscale.in
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://maektwain.com"
twitter_username: saranshlovesr
github_username:  maektwain

# Build settings
markdown: kramdown
permalink: pretty
